### ISSUE TITLE
Add "&comment=something" to all calls.

### ISSUE THREAD

**Issue by LeoMavri** [jgolla/torn-api#388]
This will let you add a comment that will show up in the API tab on Torn.
The gist of it would be that [this](https://github.com/jgolla/torn-api/blob/main/lib/TornAPIBase.ts#L138) line should be changed from:
```js
return `https://api.torn.com/${params.route}/${id}?selections=${params.selection}&key=${this.apiKey}${from}${to}${limit}${timestamp}`;
```
To:
```js
return `https://api.torn.com/${params.route}/${id}?selections=${params.selection}&key=${this.apiKey}${from}${to}${limit}${timestamp}${comment}`;
```

Where comment would be roughly: 
```js
const comment = `&comment=USER_DEFINED_COMMENT`;
```

(And the comment should be in the constructor of the `TornAPI` class and be passed to `Torn`, `Company` etc.

If there's nothing I missed I'll be more than happy to open a PR with the proposed changes:D

**Comment by jgolla** [comment]
Resolved by #397
