### ISSUE TITLE
User Basic is returning undefined

### ISSUE THREAD

**Issue by oliverkoehler** [jgolla/torn-api#621]
The user.basic method returns an error without an error description.

My call `torn.user.basic()`

I checked the uir an thats the result: `https://api.torn.com/user/undefined?selections=basic&key=XXXXXX`

`TornAPI.isError() =>true`
`tornUserBasic => undefined`

**Comment by jgolla** [comment]
@oliverkoehler I am looking into this. I think I know where the problem is, thanks for reporting. Just a heads up, I removed your key info from the description. Don't every share your key info. You should delete that key immediately.

**Comment by oliverkoehler** [comment]
Tyvm!
